---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: my-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/kumarsanu1993/argocd.git
    targetRevision: HEAD
    path: environment/staging/my_app_latest
  destination:
    server: https://kubernetes.default.svc
  syncPolicy: 
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validated=true
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
      - PruneLast=true
  